plugins:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/TrailingWhitespace:
  Enabled: true

Layout/LineLength:
  Max: 130

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Layout/AccessModifierIndentation:
  Enabled: true
  EnforcedStyle: outdent